# Generated by Django 5.2.3 on 2026-01-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('created_at',)},
        ),
    ]
